#pragma once
#include "CoreMinimal.h"
// Generated by Tools/UI/generate_runtime_theme.py; do not edit palette literals in widgets.
namespace IETheme
{
    inline FLinearColor Background() { return FLinearColor::FromSRGBColor(FColor(17, 21, 27, 255)); }
    inline FLinearColor Surface() { return FLinearColor::FromSRGBColor(FColor(26, 32, 40, 255)); }
    inline FLinearColor SurfaceRaised() { return FLinearColor::FromSRGBColor(FColor(37, 45, 56, 255)); }
    inline FLinearColor Text() { return FLinearColor::FromSRGBColor(FColor(243, 240, 232, 255)); }
    inline FLinearColor TextMuted() { return FLinearColor::FromSRGBColor(FColor(183, 192, 203, 255)); }
    inline FLinearColor Primary() { return FLinearColor::FromSRGBColor(FColor(233, 177, 90, 255)); }
    inline FLinearColor OnPrimary() { return FLinearColor::FromSRGBColor(FColor(17, 21, 27, 255)); }
    inline FLinearColor Accent() { return FLinearColor::FromSRGBColor(FColor(114, 204, 213, 255)); }
    inline FLinearColor Success() { return FLinearColor::FromSRGBColor(FColor(144, 203, 169, 255)); }
    inline FLinearColor Warning() { return FLinearColor::FromSRGBColor(FColor(233, 177, 90, 255)); }
    inline FLinearColor Error() { return FLinearColor::FromSRGBColor(FColor(255, 156, 145, 255)); }
    inline FLinearColor Outline() { return FLinearColor::FromSRGBColor(FColor(145, 160, 176, 255)); }
    inline FLinearColor Focus() { return FLinearColor::FromSRGBColor(FColor(233, 177, 90, 255)); }
    inline FLinearColor DisabledText() { return FLinearColor::FromSRGBColor(FColor(155, 166, 181, 255)); }
    inline FLinearColor DisabledSurface() { return FLinearColor::FromSRGBColor(FColor(37, 45, 56, 255)); }
    inline FLinearColor HealthPlayer() { return FLinearColor::FromSRGBColor(FColor(233, 177, 90, 255)); }
    inline FLinearColor HealthOpponent() { return FLinearColor::FromSRGBColor(FColor(114, 204, 213, 255)); }
    inline FLinearColor Stamina() { return FLinearColor::FromSRGBColor(FColor(144, 203, 169, 255)); }
    constexpr float ButtonHeight = 56.0f;
    constexpr float FocusThickness = 3.0f;
    constexpr float EnterSeconds = 0.24f;
}
