"""Generate semantic C++ presentation tokens from the reviewed UI theme JSON."""
import json
import argparse
from pathlib import Path


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Check committed header consistency without writing it')
    args=parser.parse_args()
    root=Path(__file__).resolve().parents[2]
    theme=json.loads((root/'ArtSource/UI/theme.json').read_text(encoding='utf-8'))
    target=root/'IntegrationDraft/IronEchoVisuals/Source/IronEchoVisuals/Public/IETheme.h'
    lines=['#pragma once','#include "CoreMinimal.h"','// Generated by Tools/UI/generate_runtime_theme.py; do not edit palette literals in widgets.','namespace IETheme','{']
    for name,color in theme['colors'].items():
        cpp_name=name[0].upper()+name[1:]
        rgb=[int(color[i:i+2],16) for i in (1,3,5)]
        lines.append('    inline FLinearColor {}() {{ return FLinearColor::FromSRGBColor(FColor({}, {}, {}, 255)); }}'.format(cpp_name,*rgb))
    for name,value in [('ButtonHeight',theme['metrics']['buttonHeight']),('FocusThickness',theme['metrics']['focusThickness']),('EnterSeconds',theme['motion']['enterSeconds'])]:
        lines.append('    constexpr float {} = {}f;'.format(name,float(value)))
    lines.append('}')
    content='\n'.join(lines)+'\n'
    if args.check:
        if not target.is_file() or target.read_text(encoding='utf-8') != content:
            raise SystemExit('Runtime theme header differs from JSON; run generator before commit')
        print('PASS: C++ theme header matches source tokens (no engine verification)')
        return
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(content,encoding='utf-8')
    print('Generated',target.relative_to(root))


if __name__=='__main__':
    main()
